[colors]
ansi = [ "#7a8382", "#c4746e", "#87a987", "#c4b28a", "#8ba4b0", "#a292a3", "#7E9CD8", "#c5c9c5" ]
brights = [ "#746875", "#c4746e", "#87a987", "#c4b28a", "#8ba4b0", "#a292a3", "#7E9CD8", "#c5c9c5" ]

background = "#282433"
foreground = "#9e9b93"

compose_cursor = '#ebde76'
cursor_bg = "#8ba4b0"
cursor_border = "#8ba4b0"
cursor_fg = "#8ba4b0"

selection_bg = "#a292a3"
selection_fg = "#eee9fc"

scrollbar_thumb = '#3f3951'
split = '#938aad'

[metadata]
name = 'kanagawa'
